### ISSUE TITLE
Path to data tier is broken

### ISSUE THREAD

**Issue by tdudgeon** [InformaticsMatters/mini-apps-pose-viewer#2]
the location of the data tier has changed so the pose viewer needs updating.
I made this change after which the app was redeployed:
https://github.com/InformaticsMatters/mini-apps-pose-viewer/commit/d3d958bb269cb074acbe3473f70f8f65529798b6

The change is reflected in the config.json that is deployed:
https://mini-apps.informaticsmatters.com/config.json

But I still get an 404 error from the config panel which is trying to get information from here (note the missing `/data`):
https://data.informaticsmatters.org/project 

Is this a problem in the pose viewer app?

**Comment by OliverDudgeon** [comment]
~~Ok yes this is an issue with the component library. Currently, I haven't worked out a way to consume the config.json url from an app inside the component library. I will patch it for now and work out a proper solution soon.~~

Turns out the uri method existed, so I forgot to source the uri from the config and bind it to the api singleton.

**Comment by OliverDudgeon** [comment]
This seems to be fixed now with the deployed changes.
